### ISSUE TITLE
Epic analytic graphs

### ISSUE THREAD

**Issue by julxyz** [juliscrazy/Peach#52]
Add graphs for channel/server activity and plugin usage
- [ ] Store server activity in database
- [ ] Add graphs to interface
- [ ] Store plugin activity in database

**Comment by julxyz** [comment]
maybe add summin like this

![image](https://user-images.githubusercontent.com/45462701/84157306-e1d04700-aa6a-11ea-8d10-94ca84fbf384.png)
